=== mefrinkazela/XML-Perhotelan/logperhotelan.dtd
<?xml encoding="UTF-8"?>

<!ELEMENT logperhotelan (pegawai)+>
<!ATTLIST logperhotelan
    xmlns CDATA #FIXED ''>

<!ELEMENT pegawai (nip,nama,ttl,jk,alamat,agama,statuskawin,kewarganegaraan,
                   gaji,statuspegawai)>
<!ATTLIST pegawai
    xmlns CDATA #FIXED ''>

<!ELEMENT nip (#PCDATA)>
<!ATTLIST nip
    xmlns CDATA #FIXED ''>

<!ELEMENT nama (#PCDATA)>
<!ATTLIST nama
    xmlns CDATA #FIXED ''>

<!ELEMENT ttl (#PCDATA)>
<!ATTLIST ttl
    xmlns CDATA #FIXED ''>

<!ELEMENT jk (#PCDATA)>
<!ATTLIST jk
    xmlns CDATA #FIXED ''>

<!ELEMENT alamat (kelurahan,kota,kodepos)>
<!ATTLIST alamat
    xmlns CDATA #FIXED ''>

<!ELEMENT agama (#PCDATA)>
<!ATTLIST agama
    xmlns CDATA #FIXED ''>

<!ELEMENT statuskawin (#PCDATA)>
<!ATTLIST statuskawin
    xmlns CDATA #FIXED ''>

<!ELEMENT kewarganegaraan (#PCDATA)>
<!ATTLIST kewarganegaraan
    xmlns CDATA #FIXED ''>

<!ELEMENT gaji (#PCDATA)>
<!ATTLIST gaji
    xmlns CDATA #FIXED ''>

<!ELEMENT statuspegawai (#PCDATA)>
<!ATTLIST statuspegawai
    xmlns CDATA #FIXED ''>

<!ELEMENT kelurahan (#PCDATA)>
<!ATTLIST kelurahan
    xmlns CDATA #FIXED ''>

<!ELEMENT kota (#PCDATA)>
<!ATTLIST kota
    xmlns CDATA #FIXED ''>

<!ELEMENT kodepos (#PCDATA)>
<!ATTLIST kodepos
    xmlns CDATA #FIXED ''>

=== mefrinkazela/XML-Perhotelan/perhotelan.xml
<?xml version="1.0" encoding="UTF-8"?><!DOCTYPE logperhotelan SYSTEM "logperhotelan.dtd">
<logperhotelan>
	<pegawai>
		<nip>2254001</nip>
		<nama>Kirana Puspa</nama>
		<ttl>Bandung, 19 Juli 1993</ttl>
		<jk>P</jk>
		<alamat>
			<kelurahan>Sarijadi</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Islam</agama>
		<statuskawin>Single</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>8.000.0000</gaji>
		<statuspegawai>Manager</statuspegawai>
	</pegawai>
	<pegawai>
		<nip>2254005</nip>
		<nama>Githadana Ayu</nama>
		<ttl>Surabaya, 23 Desember 1991</ttl>
		<jk>P</jk>
		<alamat>
			<kelurahan>Sukasari</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Islam</agama>
		<statuskawin>Menikah</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>7.250.000</gaji>
		<statuspegawai>Assistant Executive</statuspegawai>
	</pegawai>
	<pegawai>
		<nip>2254011</nip>
		<nama>Maulyanda</nama>
		<ttl>Aceh, 08 Agustus 1989</ttl>
		<jk>L</jk>
		<alamat>
			<kelurahan>Sukajadi</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Islam</agama>
		<statuskawin>Single</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>5.000.000</gaji>
		<statuspegawai>Supervisor</statuspegawai>
	</pegawai>
	<pegawai>
		<nip>2254013</nip>
		<nama>Ilga Anne</nama>
		<ttl>Bekasi, 29 Juni 1988</ttl>
		<jk>P</jk>
		<alamat>
			<kelurahan>Sarijadi</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Kristen</agama>
		<statuskawin>Menikah</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>4.500.000</gaji>
		<statuspegawai>Receptionist</statuspegawai>
	</pegawai>
	<pegawai>
		<nip>2254021</nip>
		<nama>Simon Manangi</nama>
		<ttl>Cirebon, 06 September 1988</ttl>
		<jk>L</jk>
		<alamat>
			<kelurahan>Cibogo</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Kristen</agama>
		<statuskawin>Single</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>6.000.000</gaji>
		<statuspegawai>Accounting</statuspegawai>
	</pegawai>
	<pegawai>
		<nip>2254033</nip>
		<nama>Shinta Amelia</nama>
		<ttl>Padang, 23 Maret 1987</ttl>
		<jk>P</jk>
		<alamat>
			<kelurahan>Ciwaruga</kelurahan>
			<kota>Bandung</kota>
			<kodepos>40151</kodepos>
		</alamat>
		<agama>Islam</agama>
		<statuskawin>Single</statuskawin>
		<kewarganegaraan>WNI</kewarganegaraan>
		<gaji>4.000.000</gaji>
		<statuspegawai>House Keeper</statuspegawai>
	</pegawai>
</logperhotelan>
